apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: dafalut
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
